name: "Reusable lint workflow"

on:
  workflow_call:

jobs:
  cmake-format:
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/hrzlgnm/cappuchin-github-void-linux-glibc-clang:v1@sha256:d2517c608e0601ceab484f9d22391c9a72a467269f5d5425e11fd5584e96a437"
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: üìê Check cmake format
        run: gersemi --check --diff .

  clang-format:
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/hrzlgnm/cappuchin-github-void-linux-glibc-clang:v1@sha256:d2517c608e0601ceab484f9d22391c9a72a467269f5d5425e11fd5584e96a437"
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: üìê Check clang-format
        run: cmake -D FORMAT_COMMAND=clang-format -P cmake/lint.cmake
