name: "Reusable lint workflow"

on:
  workflow_call:

jobs:
  clang-format:
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/hrzlgnm/cappuchin-github-void-linux-glibc-clang:v1@sha256:5ec3c16924ac51dab05dbd0c9ad8320ea8b83f4e161078d2b26a1723beb3507a"
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: üìê Check clang-format
        run: cmake -D FORMAT_COMMAND=clang-format -P cmake/lint.cmake
